PREFIX qb:<http://purl.org/linked-data/cube#>
PREFIX xo:<http://xodx.dssn.org/>
SELECT ?timeStamp (SUM(?follower*?messagesSent) AS ?messagesOut) (SUM(?messagesReceived) AS ?messagesIn)
#?messagesReceived
WHERE {
    ?observation1 xo:refTime ?timeStamp;
        xo:refAgent ?agent;
        xo:follower ?follower.
    ?observation2 xo:refTime ?timeStamp;
        xo:refAgent ?agent;
        xo:outgoingMessages ?messagesSent.
    ?observation3 xo:refTime ?timeStamp;
        xo:refAgent ?agent;
        xo:receivedMessages ?messagesReceived.
}
GROUP BY ?timeStamp
ORDER BY ?timeStamp
